In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2

Python Series

In [ ]:
list1=["Numpy","pandas","matplotib","scikit_learn"]
s1=pd.Series(list1)
print(s1)

0           Numpy
1          pandas
2       matplotib
3    scikit_learn
dtype: object

In [ ]:
s2=pd.Series(list1,index=["a","b","c","d"])
print(s2)

a           Numpy
b          pandas
c       matplotib
d    scikit_learn
dtype: object

Python DataFrame

In [ ]:
data={"Name":["supun","kamal","nimal"],"place":["india","SL","os"]}
print(data)

{'Name': ['supun', 'kamal', 'nimal'], 'place': ['india', 'SL', 'os']}

Read a CSV File

In [ ]:
data1=pd.read_csv("/vehicle.csv")

In [ ]:
print(data1)

                                              Title  \
0                 Honda Vezel Limited 2017 for sale
1              Jaguar XF Fully Loaded 2013 for sale
2          Toyota CHR GT New Face 2wd 2020 for sale
3                   Toyota CHR Toyato 2017 for sale
4           Toyota Land Cruiser Prado 2015 for sale
5           Toyota Land Cruiser Prado 2007 for sale
6                           Honda CRV 2018 for sale
7                  Mitsubishi Xpander 2019 for sale
8                   Suzuki Alto Japan 2017 for sale
9                           MG ZS SUV 2018 for sale
10    Toyota Vitz FM Safety Edition 2 2017 for sale
11            Mitsubishi Montero 2014 2013 for sale
12           Suzuki Wagon R FX Safety 2016 for sale
13         Toyota CHR NGX 50 GT Turbo 2017 for sale
14                      Suzuki Maruti 2008 for sale
15                    Peugeot 405 GLD 1995 for sale
16        Toyota CHR GT BOOST IMPULSE 2018 for sale
17                  Toyota Allion 260 2007 for sale
18                           BMW 523i 2012 for sale
19                 Mercedes Benz C350 2016 for sale
20                            Mazda 6 2016 for sale
21             Toyota Harrier Premium 2015 for sale
22          Suzuki Wagon R FZ Premium 2018 for sale
23            Suzuki Wagon R Stingray 2014 for sale
24               Honda Vezel New Face 2018 for sale
25                Toyota Aqua G Grade 2016 for sale
26                      Honda Fit GP1 2012 for sale
27  Mercedes Benz E300 BLUETEC HYBRID 2015 for sale

                                            Sub_title          Price  \
0   Posted on 01 Sep 2:45 pm, Kurunegala City, Kur...  Rs 12,900,000
1   Posted on 28 Sep 10:23 am, Kurunegala City, Ku...  Rs 16,250,000
2        Posted on 16 Sep 1:16 pm, Colombo 7, Colombo  Rs 17,000,000
3       Posted on 30 Sep 10:12 am, Colombo 7, Colombo  Rs 13,000,000
4         Posted on 30 Sep 9:50 pm, Kelaniya, Gampaha  Rs 33,500,000
5     Posted on 24 Sep 3:52 pm, Gampaha City, Gampaha  Rs 14,900,000
6     Posted on 30 Sep 8:36 am, Gampaha City, Gampaha  Rs 19,100,000
7       Posted on 29 Sep 8:23 am, Maharagama, Colombo  Rs 14,400,000
8       Posted on 01 Oct 8:29 am, Maharagama, Colombo   Rs 4,790,000
9         Posted on 25 Sep 8:18 am, Kelaniya, Gampaha   Rs 9,200,000
10          Posted on 28 Sep 8:20 am, Angoda, Colombo   Rs 7,800,000
11  Posted on 26 Sep 12:35 pm, Boralesgamuwa, Colombo  Rs 19,990,000
12        Posted on 29 Sep 8:10 am, Galle City, Galle   Rs 4,885,000
13     Posted on 30 Sep 10:30 am, Rambukkana, Kegalle  Rs 12,400,000
14      Posted on 01 Oct 8:08 am, Ruwanwella, Kegalle   Rs 1,550,000
15         Posted on 01 Oct 8:08 am, Negombo, Gampaha   Rs 1,750,000
16        Posted on 30 Sep 11:04 pm, Negombo, Gampaha  Rs 13,750,000
17        Posted on 28 Sep 7:55 am, Galle City, Galle   Rs 8,250,000
18        Posted on 28 Sep 4:13 pm, Nugegoda, Colombo  Rs 15,490,000
19  Posted on 29 Sep 9:25 am, Anuradhapura City, A...  Rs 22,000,000
20    Posted on 09 Sep 9:29 am, Gampaha City, Gampaha  Rs 15,800,000
21        Posted on 01 Oct 7:45 am, Kohuwala, Colombo  Rs 20,800,000
22          Posted on 26 Sep 8:14 pm, Ragama, Gampaha   Rs 5,700,000
23      Posted on 26 Sep 10:29 am, Katugastota, Kandy   Rs 5,400,000
24    Posted on 29 Sep 12:54 pm, Wennappuwa, Puttalam  Rs 12,800,000
25  Posted on 27 Sep 7:32 am, Embilipitiya, Ratnapura   Rs 8,050,000
26  Posted on 28 Sep 9:54 am, Kurunegala City, Kur...   Rs 5,025,000
27       Posted on 25 Sep 2:25 pm, Colombo 2, Colombo  Rs 24,500,000

            Brand               Model              Edition  Year Condition  \
0           Honda               Vezel              Limited  2017      Used
1          Jaguar                  XF         Fully Loaded  2013      Used
2          Toyota                 CHR      GT New Face 2wd  2020      Used
3          Toyota                 CHR               Toyato  2017      Used
4          Toyota  Land Cruiser Prado                prado  2015      Used
5          Toyota  Land Cruiser Prado                  NaN  2007      Used
6           Honda                 CRV                  NaN  2018      Used
7      Mitsubishi             Xpander                  NaN  2019      Used
8          Suzuki                Alto    Suzuki Alto Japan  2017      Used
9              MG                  ZS                  SUV  2018      Used
10         Toyota                Vitz  FM Safety Edition 2  2017      Used
11     Mitsubishi             Montero                 2014  2013      Used
12         Suzuki          Wagon R FX               Safety  2016      Used
13         Toyota                 CHR      NGX 50 GT Turbo  2017      Used
14         Suzuki              Maruti                  NaN  2008      Used
15        Peugeot                 405                  GLD  1995      Used
16         Toyota                 CHR     GT BOOST IMPULSE  2018      Used
17         Toyota              Allion                  260  2007      Used
18            BMW                523i                  NaN  2012      Used
19  Mercedes Benz                C350                  NaN  2016      Used
20          Mazda                   6                  NaN  2016      Used
21         Toyota             Harrier              Premium  2015      Used
22         Suzuki          Wagon R FZ              Premium  2018      Used
23         Suzuki    Wagon R Stingray                  NaN  2014      Used
24          Honda               Vezel             New Face  2018      Used
25         Toyota                Aqua              G Grade  2016      Used
26          Honda                 Fit                  GP1  2012      Used
27  Mercedes Benz                E300       BLUETEC HYBRID  2015      Used

   Transmission       Body    Fuel  Capacity     Mileage  \
0     Automatic  SUV / 4x4  Hybrid  1,500 cc   37,000 km
1     Automatic     Saloon  Diesel  2,200 cc   42,000 km
2     Automatic  SUV / 4x4  Petrol  1,200 cc   15,000 km
3     Automatic  SUV / 4x4  Petrol  1,200 cc   21,000 km
4     Automatic  SUV / 4x4  Petrol  2,700 cc   57,000 km
5     Automatic  SUV / 4x4  Petrol  2,700 cc  120,000 km
6     Automatic  SUV / 4x4  Petrol  1,500 cc   37,134 km
7     Automatic        NaN  Petrol  1,500 cc   50,500 km
8     Automatic  Hatchback  Petrol    650 cc   46,521 km
9     Automatic  SUV / 4x4  Petrol  1,000 cc   60,000 km
10    Automatic  Hatchback  Petrol  1,000 cc   29,000 km
11    Automatic  SUV / 4x4  Diesel  3,200 cc  110,000 km
12    Automatic  Hatchback  Petrol    650 cc   68,000 km
13    Automatic  SUV / 4x4  Petrol  1,200 cc   37,000 km
14       Manual  Hatchback  Petrol    800 cc  113,000 km
15       Manual     Saloon  Diesel  1,905 cc  150,000 km
16    Automatic        NaN  Petrol  1,200 cc   26,000 km
17    Automatic     Saloon  Petrol  1,800 cc  115,000 km
18    Automatic        NaN  Petrol  2,000 cc   49,000 km
19    Automatic     Saloon  Hybrid  2,000 cc  146,000 km
20    Automatic     Saloon  Petrol  2,000 cc   79,000 km
21    Automatic  SUV / 4x4  Hybrid  2,500 cc   92,000 km
22    Automatic  Hatchback  Hybrid    660 cc   20,300 km
23    Automatic  Hatchback  Petrol    650 cc   43,400 km
24    Automatic        NaN  Petrol  1,500 cc   34,000 km
25    Automatic  Hatchback  Petrol  1,500 cc   49,750 km
26    Automatic  Hatchback  Hybrid  1,300 cc  108,000 km
27    Tiptronic     Saloon  Diesel  2,143 cc   53,000 km

                             Location  \
0        Kurunegala City,  Kurunegala
1        Kurunegala City,  Kurunegala
2                 Colombo 7,  Colombo
3                 Colombo 7,  Colombo
4                  Kelaniya,  Gampaha
5              Gampaha City,  Gampaha
6              Gampaha City,  Gampaha
7                Maharagama,  Colombo
8                Maharagama,  Colombo
9                  Kelaniya,  Gampaha
10                   Angoda,  Colombo
11            Boralesgamuwa,  Colombo
12                 Galle City,  Galle
13               Rambukkana,  Kegalle
14               Ruwanwella,  Kegalle
15                  Negombo,  Gampaha
16                  Negombo,  Gampaha
17                 Galle City,  Galle
18                 Nugegoda,  Colombo
19   Anuradhapura City,  Anuradhapura
20             Gampaha City,  Gampaha
21                 Kohuwala,  Colombo
22                   Ragama,  Gampaha
23                Katugastota,  Kandy
24              Wennappuwa,  Puttalam
25           Embilipitiya,  Ratnapura
26       Kurunegala City,  Kurunegala
27                Colombo 2,  Colombo

                                          Description  \
0   HONDA VEZEL LIMITEDCBE-XXXXMANU YEAR : 2017LIM...
1   1st owner(registered owner)Diesel(13-14km per ...
2   2020 Facelift modelFirst owner (No previous ow...
3   Toyota CHR GT Turbo1st owner Imported as a bra...
4   Toyota Land Cruiser Prado 20152 nd Owner for 5...
5   0719467796    14900000/=Toyota Land Cruiser Pr...
6   HONDA CRV  VTI L TURBO, 7 SEATER,SUNROOF,WP CB...
7   Mitsubishi Xpander Jeep For Sale In Maharagama...
8   70% Leasing Arrange ,small Down Payment only  ...
9   TURBOCHARGED ENGINE, FIRST OWNER, SUN ROOF, PA...
10  Safety edition 2Registered 2019 JulyA personal...
11  1st owner  2014 registered 2013 manufactured. ...
12  Wagon r FXYear of manufacture 2016Year of regi...
13  Personally imported for the Permit, All import...
14                                    A/c working ...
15  ûìªªŒª?Engine goodûìªªŒª?Good running condit...
16  ûìªªŒª? TOYOTA CH-R GT BOOST IMPULSE NGX 10ûì...
17  2007 YOM2010 Register2nd OwnerLCD Touchscreen ...
18  ûìªªŒª?BMW 523i M Sport ûìªªŒª?2012 ûìªªŒª?...
19  Premium plus package Perfume package Head up d...
20  YOM 2016YOR 2016 û›ª¤ª?û?ª?ªŠThe only 2L mazda...
21  1st Owner, Premium Grade, Leather Electric Sea...
22  SUZUKI WAGON R FZ - PREMIUMAMW Brand New Impor...
23  Suzuki Wagon R StingrayOwnership : 1st owner.R...
24  Honda Vezel Rs Sensing Facelift Model Manufact...
25  Used by women ,good condition ,first owner ,ow...
26  Honda Fit GP1Automatic transmission Manufactur...
27  MERCEDES BENZ 2015 BLUTEC HYBRID NIGHT EDITION...

                                             Post_URL  \
0   https://ikman.lk/en/ad/honda-vezel-limited-201...
1   https://ikman.lk/en/ad/jaguar-xf-fully-loaded-...
2   https://ikman.lk/en/ad/toyota-chr-gt-new-face-...
3   https://ikman.lk/en/ad/toyota-chr-toyato-2017-...
4   https://ikman.lk/en/ad/toyota-land-cruiser-pra...
5   https://ikman.lk/en/ad/toyota-land-cruiser-pra...
6   https://ikman.lk/en/ad/honda-crv-2018-for-sale...
7   https://ikman.lk/en/ad/mitsubishi-xpander-2019...
8   https://ikman.lk/en/ad/suzuki-alto-japan-2017-...
9   https://ikman.lk/en/ad/mg-zs-suv-2018-for-sale...
10  https://ikman.lk/en/ad/toyota-vitz-fm-safety-e...
11  https://ikman.lk/en/ad/mitsubishi-montero-2014...
12  https://ikman.lk/en/ad/suzuki-wagon-r-fx-safet...
13  https://ikman.lk/en/ad/toyota-chr-ngx-50-gt-tu...
14  https://ikman.lk/en/ad/suzuki-maruti-2008-for-...
15  https://ikman.lk/en/ad/peugeot-405-gld-1995-fo...
16  https://ikman.lk/en/ad/toyota-chr-gt-boost-imp...
17  https://ikman.lk/en/ad/toyota-allion-260-2007-...
18  https://ikman.lk/en/ad/bmw-523i-2012-for-sale-...
19  https://ikman.lk/en/ad/mercedes-benz-c350-2016...
20  https://ikman.lk/en/ad/mazda-6-2016-for-sale-g...
21  https://ikman.lk/en/ad/toyota-harrier-premium-...
22  https://ikman.lk/en/ad/suzuki-wagon-r-fz-premi...
23  https://ikman.lk/en/ad/suzuki-wagon-r-stingray...
24  https://ikman.lk/en/ad/honda-vezel-new-face-20...
25  https://ikman.lk/en/ad/toyota-aqua-g-grade-201...
26  https://ikman.lk/en/ad/honda-fit-gp1-2012-for-...
27  https://ikman.lk/en/ad/mercedes-benz-e300-blue...

                                          Seller_name     Seller_type  \
0                                  Prasad Enterprises  Premium-Member
1                                 Dhanushka Dharmasri          Member
2                                       Carzone Lanka          Member
3                                       Carzone Lanka          Member
4                                  Shine Music Center          Member
5                                            Tharusha          Member
6                                          RAJAPAKSHA          Member
7   Sell fast | Dolahena | û?ª?ª?û?ª?ªˆû?ª?ªñû?ª?ª...          Member
8                                     MAC Enterprises  Premium-Member
9                                 Ranjith Edirisingha          Member
10                                     Dilanka Prasad  Premium-Member
11                                           Bhathiya  Premium-Member
12                                               Deen          Member
13                               Chirantha Jayasinghe          Member
14                                             Asanka          Member
15                                       sasith Devin          Member
16                                          MR Amjath          Member
17                    Sell Fast | Tangalle | ICT Zone          Member
18                                    Janith Kumarage          Member
19                                            Muditha  Premium-Member
20                                             Dulina  Premium-Member
21                                        Krish Carz   Premium-Member
22                    Sell fast | Weliweriya | CS Ads          Member
23                                        RMS Kanthie  Premium-Member
24                                            Antonex          Member
25                                            dilshan  Premium-Member
26                                            suranga  Premium-Member
27                           Darshana Wijesiriwardana          Member

     published_date  Review
0    9/1/2022 14:45   V.Bad
1   9/28/2022 10:23    Good
2   9/16/2022 13:16      Ok
3   9/30/2022 10:12     Bad
4   9/30/2022 21:50  V.Good
5   9/24/2022 15:52   V.Bad
6    9/30/2022 8:36     Bad
7    9/29/2022 8:23     Bad
8    10/1/2022 8:29     Bad
9    9/25/2022 8:18   V.Bad
10   9/28/2022 8:20    Good
11  9/26/2022 12:35  V.Good
12   9/29/2022 8:10      Ok
13  9/30/2022 10:30      Ok
14   10/1/2022 8:08     Bad
15   10/1/2022 8:08      Ok
16  9/30/2022 23:04    Good
17   9/28/2022 7:55  V.Good
18  9/28/2022 16:13     Bad
19   9/29/2022 9:25     Bad
20    9/9/2022 9:29      Ok
21   10/1/2022 7:45   V.Bad
22  9/26/2022 20:14      Ok
23  9/26/2022 10:29      Ok
24  9/29/2022 12:54  V.Good
25   9/27/2022 7:32     Bad
26   9/28/2022 9:54  V.Good
27  9/25/2022 14:25   V.Bad

In [ ]:
df2=pd.DataFrame(data1)
df2.head()

,Title,Sub_title,Price,Brand,Model,Edition,Year,Condition,Transmission,Body,Fuel,Capacity,Mileage,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Review
0,Honda Vezel Limited 2017 for sale,"Posted on 01 Sep 2:45 pm, Kurunegala City, Kur...","Rs 12,900,000",Honda,Vezel,Limited,2017,Used,Automatic,SUV / 4x4,Hybrid,"1,500 cc","37,000 km","Kurunegala City, Kurunegala",HONDA VEZEL LIMITEDCBE-XXXXMANU YEAR : 2017LIM...,https://ikman.lk/en/ad/honda-vezel-limited-201...,Prasad Enterprises,Premium-Member,9/1/2022 14:45,V.Bad
1,Jaguar XF Fully Loaded 2013 for sale,"Posted on 28 Sep 10:23 am, Kurunegala City, Ku...","Rs 16,250,000",Jaguar,XF,Fully Loaded,2013,Used,Automatic,Saloon,Diesel,"2,200 cc","42,000 km","Kurunegala City, Kurunegala",1st owner(registered owner)Diesel(13-14km per ...,https://ikman.lk/en/ad/jaguar-xf-fully-loaded-...,Dhanushka Dharmasri,Member,9/28/2022 10:23,Good
2,Toyota CHR GT New Face 2wd 2020 for sale,"Posted on 16 Sep 1:16 pm, Colombo 7, Colombo","Rs 17,000,000",Toyota,CHR,GT New Face 2wd,2020,Used,Automatic,SUV / 4x4,Petrol,"1,200 cc","15,000 km","Colombo 7, Colombo",2020 Facelift modelFirst owner (No previous ow...,https://ikman.lk/en/ad/toyota-chr-gt-new-face-...,Carzone Lanka,Member,9/16/2022 13:16,Ok
3,Toyota CHR Toyato 2017 for sale,"Posted on 30 Sep 10:12 am, Colombo 7, Colombo","Rs 13,000,000",Toyota,CHR,Toyato,2017,Used,Automatic,SUV / 4x4,Petrol,"1,200 cc","21,000 km","Colombo 7, Colombo",Toyota CHR GT Turbo1st owner Imported as a bra...,https://ikman.lk/en/ad/toyota-chr-toyato-2017-...,Carzone Lanka,Member,9/30/2022 10:12,Bad
4,Toyota Land Cruiser Prado 2015 for sale,"Posted on 30 Sep 9:50 pm, Kelaniya, Gampaha","Rs 33,500,000",Toyota,Land Cruiser Prado,prado,2015,Used,Automatic,SUV / 4x4,Petrol,"2,700 cc","57,000 km","Kelaniya, Gampaha",Toyota Land Cruiser Prado 20152 nd Owner for 5...,https://ikman.lk/en/ad/toyota-land-cruiser-pra...,Shine Music Center,Member,9/30/2022 21:50,V.Good

In [ ]:
df2=pd.DataFrame(data1)
print(df2.head())

                                      Title  \
0         Honda Vezel Limited 2017 for sale
1      Jaguar XF Fully Loaded 2013 for sale
2  Toyota CHR GT New Face 2wd 2020 for sale
3           Toyota CHR Toyato 2017 for sale
4   Toyota Land Cruiser Prado 2015 for sale

                                           Sub_title          Price   Brand  \
0  Posted on 01 Sep 2:45 pm, Kurunegala City, Kur...  Rs 12,900,000   Honda
1  Posted on 28 Sep 10:23 am, Kurunegala City, Ku...  Rs 16,250,000  Jaguar
2       Posted on 16 Sep 1:16 pm, Colombo 7, Colombo  Rs 17,000,000  Toyota
3      Posted on 30 Sep 10:12 am, Colombo 7, Colombo  Rs 13,000,000  Toyota
4        Posted on 30 Sep 9:50 pm, Kelaniya, Gampaha  Rs 33,500,000  Toyota

                Model          Edition  Year Condition Transmission  \
0               Vezel          Limited  2017      Used    Automatic
1                  XF     Fully Loaded  2013      Used    Automatic
2                 CHR  GT New Face 2wd  2020      Used    Automatic
3                 CHR           Toyato  2017      Used    Automatic
4  Land Cruiser Prado            prado  2015      Used    Automatic

        Body    Fuel  Capacity    Mileage                       Location  \
0  SUV / 4x4  Hybrid  1,500 cc  37,000 km   Kurunegala City,  Kurunegala
1     Saloon  Diesel  2,200 cc  42,000 km   Kurunegala City,  Kurunegala
2  SUV / 4x4  Petrol  1,200 cc  15,000 km            Colombo 7,  Colombo
3  SUV / 4x4  Petrol  1,200 cc  21,000 km            Colombo 7,  Colombo
4  SUV / 4x4  Petrol  2,700 cc  57,000 km             Kelaniya,  Gampaha

                                         Description  \
0  HONDA VEZEL LIMITEDCBE-XXXXMANU YEAR : 2017LIM...
1  1st owner(registered owner)Diesel(13-14km per ...
2  2020 Facelift modelFirst owner (No previous ow...
3  Toyota CHR GT Turbo1st owner Imported as a bra...
4  Toyota Land Cruiser Prado 20152 nd Owner for 5...

                                            Post_URL          Seller_name  \
0  https://ikman.lk/en/ad/honda-vezel-limited-201...   Prasad Enterprises
1  https://ikman.lk/en/ad/jaguar-xf-fully-loaded-...  Dhanushka Dharmasri
2  https://ikman.lk/en/ad/toyota-chr-gt-new-face-...        Carzone Lanka
3  https://ikman.lk/en/ad/toyota-chr-toyato-2017-...        Carzone Lanka
4  https://ikman.lk/en/ad/toyota-land-cruiser-pra...   Shine Music Center

      Seller_type   published_date  Review
0  Premium-Member   9/1/2022 14:45   V.Bad
1          Member  9/28/2022 10:23    Good
2          Member  9/16/2022 13:16      Ok
3          Member  9/30/2022 10:12     Bad
4          Member  9/30/2022 21:50  V.Good

In [ ]:
print(df2.ndim)
print(df2.shape)
df2.info()

2
(28, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Title           28 non-null     object
 1   Sub_title       28 non-null     object
 2   Price           28 non-null     object
 3   Brand           28 non-null     object
 4   Model           28 non-null     object
 5   Edition         20 non-null     object
 6   Year            28 non-null     int64
 7   Condition       28 non-null     object
 8   Transmission    28 non-null     object
 9   Body            24 non-null     object
 10  Fuel            28 non-null     object
 11  Capacity        28 non-null     object
 12  Mileage         28 non-null     object
 13  Location        28 non-null     object
 14  Description     28 non-null     object
 15  Post_URL        28 non-null     object
 16  Seller_name     28 non-null     object
 17  Seller_type     28 non-null     object
 18  published_date  28 non-null     object
 19  Review          28 non-null     object
dtypes: int64(1), object(19)
memory usage: 4.5+ KB